### ISSUE TITLE
Get song streaming/synchronization working

### ISSUE THREAD

**Issue by jjcm** [nthitz/mashupfm#2]

**Comment by nthitz** [comment]
Right now things aren't really synced up. Everyone listens to the same song, but not necessarily at the same second of the song. Some users start it before others. Should be straightforward to just change the playback time to a certain offset so everyone is in sync. This more or less what you mean?

**Comment by nthitz** [comment]
fixed in 112d5231ebe410cc38d2a4112ad65c436ab6d180
